const supabase=window.supabase.createClient("https://iuwmdwbdkegyzkppvngw.supabase.co","sb_publishable_tXm0KC_lp8lSMh0QkdpCxA_jG_sm1hq");
const $=id=>document.getElementById(id);let user=null,genres=[],editing=null,currentNovel=null;
async function boot(){const r=await supabase.auth.getUser();user=r.data.user;if(!user){location.href="index.html";return}const p=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();if(p.error||p.data?.role!=="admin"){$("gate").innerHTML="<h2>Access denied</h2><p>This area is for the INKORA administrator only.</p><a href='novel.html'>Return to INKORA</a>";return}$("gate").classList.add("hidden");$("app").classList.remove("hidden");await loadGenres();await loadNovels();wire()}
function wire(){$("newNovel").onclick=()=>openForm();$("cancel").onclick=()=>openForm();$("novelForm").onsubmit=saveNovel;$("storySearch").oninput=loadNovels;$("logout").onclick=async()=>{await supabase.auth.signOut();location.href="novel.html"};$("closeChapters").onclick=clearChapters;$("chapterForm").onsubmit=saveChapter;$("cancelChapter").onclick=()=>resetChapterForm()}
async function loadGenres(){const r=await supabase.from("novel_genres").select("id,name").eq("is_active",true).order("sort_order");if(r.error){$("formMsg").textContent=r.error.message;return}genres=r.data||[];$("genre").innerHTML=genres.map(g=>"<option value='"+g.id+"'>"+esc(g.name)+"</option>").join("")}
async function loadNovels(){const term=$("storySearch").value.trim();let q=supabase.from("novels").select("*,novel_genres(name)").order("created_at",{ascending:false});if(term)q=q.ilike("title","%"+term+"%");const r=await q;if(r.error){$("storyList").innerHTML="<p>"+esc(r.error.message)+"</p>";return}const rows=r.data||[];$("statNovels").textContent=rows.length;$("statPublished").textContent=rows.filter(x=>x.is_published).length;$("statViews").textContent=rows.reduce((s,x)=>s+Number(x.views||0),0).toLocaleString();const ids=rows.map(x=>x.id);if(ids.length){const c=await supabase.from("novel_chapters").select("id,novel_id");$("statChapters").textContent=(c.data||[]).length}else $("statChapters").textContent="0";$("storyList").innerHTML=rows.map(n=>'<article class="story-row"><img src="'+esc(n.cover_url||"")+'" alt=""><div><h3>'+esc(n.title)+'</h3><small>'+esc(n.author_name||"Unknown")+' · '+esc(n.novel_genres?.name||"Story")+' · '+(n.is_published?"Published":"Draft")+'</small></div><div><button data-edit="'+n.id+'">Edit</button><button data-ch="'+n.id+'">Chapters</button></div></article>').join("")||"<p>No stories yet.</p>";document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>editNovel(b.dataset.edit));document.querySelectorAll("[data-ch]").forEach(b=>b.onclick=()=>openChapters(b.dataset.ch))}
async function saveNovel(e){e.preventDefault();const title=$("title").value.trim();if(!title)return;$("formMsg").textContent="Saving…";const payload={title,slug:slugify(title),author_name:$("author").value.trim()||"Unknown author",genre_id:$("genre").value||null,status:$("status").value,synopsis:$("synopsis").value.trim(),chapter_count:Number($("chapterCount").value||0),is_featured:$("featured").checked,is_trending:$("trending").checked,is_published:$("published").checked,updated_at:new Date().toISOString()};try{const file=$("cover").files?.[0];if(file){if(file.size>10*1024*1024)throw new Error("Cover must be under 10MB.");const ext=(file.name.split(".").pop()||"jpg").toLowerCase(),path=user.id+"/"+Date.now()+"-"+slugify(title)+"."+ext;const up=await supabase.storage.from("inkora-covers").upload(path,file,{upsert:false,contentType:file.type,cacheControl:"3600"});if(up.error)throw new Error("Cover upload failed: "+up.error.message);payload.cover_url=supabase.storage.from("inkora-covers").getPublicUrl(path).data.publicUrl}let r;if(editing)r=await supabase.from("novels").update(payload).eq("id",editing);else r=await supabase.from("novels").insert(payload);if(r.error)throw new Error(r.error.message);$("formMsg").textContent="Story saved successfully.";openForm();await loadNovels()}catch(e){$("formMsg").textContent=e.message||"Save failed."}}
async function editNovel(id){const r=await supabase.from("novels").select("*").eq("id",id).single();if(r.error)return;$("formTitle").textContent="Edit story";$("cancel").classList.remove("hidden");editing=id;const n=r.data;$("title").value=n.title||"";$("author").value=n.author_name||"";$("genre").value=n.genre_id||"";$("status").value=n.status||"ongoing";$("synopsis").value=n.synopsis||"";$("chapterCount").value=n.chapter_count||0;$("featured").checked=!!n.is_featured;$("trending").checked=!!n.is_trending;$("published").checked=!!n.is_published;window.scrollTo({top:0,behavior:"smooth"})}
function openForm(){if(editing){editing=null;$("novelForm").reset();$("published").checked=true}$("formTitle").textContent="Add a story";$("cancel").classList.add("hidden");if(!editing)$("formMsg").textContent=""}
async function openChapters(id){currentNovel=id;const n=await supabase.from("novels").select("title").eq("id",id).single();$("chapterHeading").textContent=(n.data?.title||"Story")+" — Chapters";$("chapterHint").textContent="Add, edit and publish chapters.";$("chapterForm").classList.remove("hidden");await loadChapters()}
async function loadChapters(){if(!currentNovel)return;const r=await supabase.from("novel_chapters").select("*").eq("novel_id",currentNovel).order("chapter_number");if(r.error){$("chapterList").innerHTML="<p>"+esc(r.error.message)+"</p>";return}$("chapterList").innerHTML=(r.data||[]).map(c=>'<div class="chapter-row"><div><strong>Chapter '+c.chapter_number+'</strong> · '+esc(c.title)+'<small> · '+(c.is_published?"Published":"Draft")+'</small></div><div><button data-ce="'+c.id+'">Edit</button><button data-cd="'+c.id+'">Delete</button></div></div>').join("")||"<p>No chapters yet.</p>";document.querySelectorAll("[data-ce]").forEach(b=>b.onclick=()=>editChapter(b.dataset.ce));document.querySelectorAll("[data-cd]").forEach(b=>b.onclick=()=>deleteChapter(b.dataset.cd))}
async function saveChapter(e){e.preventDefault();const payload={novel_id:currentNovel,chapter_number:Number($("chapterNumber").value),title:$("chapterTitle").value.trim(),content:$("chapterContent").value,is_published:$("chapterPublished").checked,updated_at:new Date().toISOString()};if(!payload.chapter_number||!payload.title||!payload.content)return;const id=$("chapterId").value;const r=id?await supabase.from("novel_chapters").update(payload).eq("id",id):await supabase.from("novel_chapters").insert(payload);if(r.error){alert(r.error.message);return}resetChapterForm();await loadChapters();await loadNovels()}
async function editChapter(id){const r=await supabase.from("novel_chapters").select("*").eq("id",id).single();if(r.error)return;const c=r.data;$("chapterId").value=c.id;$("chapterNumber").value=c.chapter_number;$("chapterTitle").value=c.title;$("chapterContent").value=c.content;$("chapterPublished").checked=!!c.is_published;document.getElementById("chapterForm").scrollIntoView({behavior:"smooth"})}
async function deleteChapter(id){if(!confirm("Delete this chapter?"))return;const r=await supabase.from("novel_chapters").delete().eq("id",id);if(r.error)alert(r.error.message);else{await loadChapters();await loadNovels()}}
function resetChapterForm(){$("chapterForm").reset();$("chapterId").value="";$("chapterPublished").checked=true}
function clearChapters(){currentNovel=null;$("chapterForm").classList.add("hidden");$("chapterHeading").textContent="Chapters";$("chapterHint").textContent="Select a story to manage chapters.";$("chapterList").innerHTML=""}
function slugify(s){return s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,90)}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",""":"&quot;","'":"&#039;"}[c]))}
boot();