const SUPABASE_URL="https://iuwmdwbdkegyzkppvngw.supabase.co";
const SUPABASE_KEY="sb_publishable_tXm0KC_lp8lSMh0QkdpCxA_jG_sm1hq";
const supabaseClient=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const menu=$("#mobileMenu"),backdrop=$("#menuBackdrop"),modal=$("#loginModal"),toast=$("#toast");
function openMenu(){menu.classList.add("open");backdrop.classList.add("open")}function closeMenu(){menu.classList.remove("open");backdrop.classList.remove("open")}
function openLogin(){modal.classList.add("open");renderAuthState()}function closeLogin(){modal.classList.remove("open")}
$("#menuBtn").onclick=openMenu;$("#menuClose").onclick=closeMenu;backdrop.onclick=closeMenu;$("#loginBtn").onclick=openLogin;$("#mobileLogin").onclick=()=>{closeMenu();openLogin()};$$("[data-close]").forEach(x=>x.onclick=closeLogin);
document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeMenu();closeLogin()}});
const searchPanel=$("#searchPanel"),searchInput=$("#searchInput"),results=$("#searchResults");
$("#searchBtn").onclick=()=>{searchPanel.classList.toggle("open");if(searchPanel.classList.contains("open"))searchInput.focus()};$("#searchClose").onclick=()=>searchPanel.classList.remove("open");
const searchable=[["Graphic Design","Flyers, posters, banners, invitations and social media designs.","#services"],["Logo & Branding","Logos, brand identity and business stationery.","#services"],["Photo Editing","Retouching, background replacement and enhancement.","#services"],["Video Editing","Reels, promotional, church and event videos.","#services"],["Web Design","Business, portfolio, booking and e-commerce websites.","#services"],["Pricing","Starting prices and service packages.","#pricing"],["Portfolio","Selected creative work and project categories.","#portfolio"]];
searchInput.oninput=()=>{const q=searchInput.value.trim().toLowerCase();if(!q){results.innerHTML="";return}const hits=searchable.filter(x=>(x[0]+" "+x[1]).toLowerCase().includes(q)).slice(0,5);results.innerHTML=hits.length?hits.map(x=>`<a href="${x[2]}"><strong>${x[0]}</strong><br>${x[1]}</a>`).join(""):"No matching service found.";results.querySelectorAll("a").forEach(a=>a.onclick=()=>searchPanel.classList.remove("open"))};
$$(".filter").forEach(btn=>btn.onclick=()=>{$$(".filter").forEach(b=>b.classList.remove("active"));btn.classList.add("active");const cat=btn.dataset.filter;$$(".work-card").forEach(card=>card.style.display=cat==="all"||card.dataset.cat===cat?"block":"none")});
const serviceSelect=$("#serviceSelect");$$("[data-service]").forEach(btn=>btn.onclick=()=>{serviceSelect.value=btn.dataset.service});
function showToast(msg){toast.textContent=msg;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),3500)}
async function showPasswordReset(){const m=document.querySelector(".modal");if(!m)return;m.innerHTML=`<button class="modal-close" data-close>×</button><img src="https://raw.githubusercontent.com/lighthousefamily828-netizen/damoma-digital-studio/main/assets/damoma-logo.webp?v=4" alt="Damoma"><span class="kicker">PASSWORD RESET</span><h2>Set a new password.</h2><p>Choose a new password of at least 6 characters.</p><input id="newPassword" type="password" placeholder="New password"><input id="newPassword2" type="password" placeholder="Confirm new password"><button class="btn btn-gold full" id="updatePassword">Update Password</button>`;m.querySelector("[data-close]").onclick=closeLogin;m.querySelector("#updatePassword").onclick=async()=>{const p=$("#newPassword").value,p2=$("#newPassword2").value;if(p.length<6)return showToast("Password must be at least 6 characters.");if(p!==p2)return showToast("Passwords do not match.");const {error}=await supabaseClient.auth.updateUser({password:p});if(error)return showToast(error.message);showToast("Password updated successfully. You can now sign in.");await supabaseClient.auth.signOut();setTimeout(renderAuthState,400)}}
async function forgotPassword(){const email=$("#authEmail")?.value.trim();if(!email)return showToast("Enter your email address first.");const {error}=await supabaseClient.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+"/"});if(error)return showToast(error.message);showToast("Password reset email sent. Check your inbox.");}
async function authMarkup(user){const m=document.querySelector(".modal");if(!m)return;if(user){let isAdmin=false;if(supabaseClient){const {data}=await supabaseClient.from("profiles").select("role").eq("id",user.id).maybeSingle();isAdmin=data?.role==="admin"}m.innerHTML=`<button class="modal-close" data-close>×</button><img src="https://raw.githubusercontent.com/lighthousefamily828-netizen/damoma-digital-studio/main/assets/damoma-logo.webp?v=4" alt="Damoma"><span class="kicker">${isAdmin?"DAMOMA ADMIN":"CLIENT ACCOUNT"}</span><h2>You’re signed in.</h2><p>${user.email||""}</p>${isAdmin?'<a class="btn btn-gold full" href="admin.html">Open Admin Dashboard →</a>':""}<button class="btn btn-gold full" id="signOut">Sign out</button>`;m.querySelector("[data-close]").onclick=closeLogin;m.querySelector("#signOut").onclick=async()=>{await supabaseClient.auth.signOut();showToast("Signed out.");renderAuthState()}}else{m.innerHTML=`<button class="modal-close" data-close>×</button><img src="https://raw.githubusercontent.com/lighthousefamily828-netizen/damoma-digital-studio/main/assets/damoma-logo.webp?v=4" alt="Damoma"><span class="kicker">CLIENT ACCOUNT</span><h2>Welcome.</h2><p>Sign in to keep your client account available across devices.</p><input id="authEmail" type="email" placeholder="Email address"><input id="authPassword" type="password" placeholder="Password (6+ characters)"><button class="btn btn-gold full" id="signIn">Login</button><button class="forgot-password" id="forgotPassword">Forgot Password?</button><div class="or">OR</div><button class="create-account" id="signUp">Create an Account</button>`;m.querySelector("[data-close]").onclick=closeLogin;m.querySelector("#signIn").onclick=signIn;m.querySelector("#forgotPassword").onclick=forgotPassword;m.querySelector("#signUp").onclick=signUp}}
async function renderAuthState(){if(!supabaseClient)return;const {data}=await supabaseClient.auth.getUser();authMarkup(data.user)}
async function signIn(){const email=$("#authEmail").value.trim(),password=$("#authPassword").value;if(!email||!password)return showToast("Enter your email and password.");const {error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)return showToast(error.message);showToast("Welcome back.");renderAuthState()}
async function signUp(){const email=$("#authEmail").value.trim(),password=$("#authPassword").value;if(!email||password.length<6)return showToast("Use a valid email and a password of at least 6 characters.");const {data,error}=await supabaseClient.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin+"/"}});if(error)return showToast(error.message);if(data.session){showToast("Account created. You are signed in.");renderAuthState()}else{showToast("Account created. Check your email and tap Confirm Email.");}}
$("#bookingForm").onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),name=fd.get("name"),contact=fd.get("contact"),service=fd.get("service")||"General enquiry",details=fd.get("details");let stored=false;if(supabaseClient){const {data:{user}}=await supabaseClient.auth.getUser();const {error}=await supabaseClient.from("project_requests").insert({name,contact,service,details,user_id:user?.id||null});stored=!error}const message=`Hello Damoma Creative Studio,%0A%0AI'd like to book a service.%0A%0AName: ${encodeURIComponent(name)}%0AContact: ${encodeURIComponent(contact)}%0AService: ${encodeURIComponent(service)}%0AProject details: ${encodeURIComponent(details)}`;window.open(`https://wa.me/2349064505247?text=${message}`,"_blank");showToast(stored?"Request saved and WhatsApp opened.":"WhatsApp opened with your project brief.");e.currentTarget.reset()};
if(supabaseClient)supabaseClient.auth.onAuthStateChange((event)=>{if(event==="PASSWORD_RECOVERY"){modal.classList.add("open");showPasswordReset()}});
renderAuthState();