const $=id=>document.getElementById(id);let user=null,genres=[],selectedNovel=null;

document.addEventListener('DOMContentLoaded',async()=>{bind();const {data}=await supabase.auth.getUser();user=data.user||null;if(!user){showGate('Please sign in first.');return}await checkAdmin();supabase.auth.onAuthStateChange(async(_e,s)=>{user=s?.user||null;if(user)checkAdmin();});});
function bind(){$('logout').onclick=async()=>{await supabase.auth.signOut();location.href='index.html'};$('novelForm').onsubmit=saveNovel;$('resetNovel').onclick=resetNovel;$('chapterForm').onsubmit=saveChapter;$('resetChapter').onclick=resetChapter;}
async function checkAdmin(){const {data,error}=await supabase.from('profiles').select('role,display_name').eq('id',user.id).single();if(error||!data){showGate('Your profile is not ready yet. Sign out and sign in again.');return}if(data.role!=='admin'){showGate('This account is not an administrator. Ask the site owner to grant admin access.');return}$('gate').classList.add('hidden');$('dashboard').classList.remove('hidden');await loadGenres();await loadNovels();}
function showGate(t){$('gateMsg').textContent=t;$('gate').classList.remove('hidden');$('dashboard').classList.add('hidden')}
async function loadGenres(){const {data}=await supabase.from('genres').select('id,name,slug').order('name');genres=data||[];$('genre').innerHTML=genres.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('')}
async function loadNovels(){const {data,error}=await supabase.from('novels').select('*').order('created_at',{ascending:false});if(error){$('novelList').textContent=error.message;return}$('novelList').innerHTML=(data||[]).map(n=>`<div class="row"><div><strong>${esc(n.title)}</strong><small>${esc(n.author_name)} · ${n.status} · ${n.is_published?'Published':'Draft'}</small></div><div class="row-actions"><button class="btn secondary-btn" onclick="editNovel('${n.id}')">Edit</button><button class="btn secondary-btn" onclick="manageChapters('${n.id}')">Chapters</button><button class="btn danger-btn" onclick="deleteNovel('${n.id}')">Delete</button></div></div>`).join('')||'<p>No novels yet.</p>'}
async function saveNovel(e){e.preventDefault();const id=$('novelId').value;const payload={title:$('title').value.trim(),author_name:$('author').value.trim(),slug:$('slug').value.trim().toLowerCase().replace(/[^a-z0-9-]+/g,'-'),cover_url:$('cover').value.trim()||null,description:$('description').value.trim()||null,status:$('status').value,is_featured:$('featured').checked,is_published:$('published').checked,updated_at:new Date().toISOString()};let res=id?await supabase.from('novels').update(payload).eq('id',id):await supabase.from('novels').insert(payload).select().single();if(res.error){$('novelMsg').textContent=res.error.message;return}const novel=res.data||{id};if(!id)await setGenres(novel.id);else await setGenres(id);$('novelMsg').textContent='Novel saved.';resetNovel();await loadNovels();}
async function setGenres(novelId){await supabase.from('novel_genres').delete().eq('novel_id',novelId);const ids=[...$('genre').selectedOptions].map(o=>({novel_id:novelId,genre_id:o.value}));if(ids.length)await supabase.from('novel_genres').insert(ids)}
window.editNovel=async id=>{const {data}=await supabase.from('novels').select('*').eq('id',id).single();if(!data)return;$('novelId').value=data.id;$('title').value=data.title;$('author').value=data.author_name;$('slug').value=data.slug;$('cover').value=data.cover_url||'';$('description').value=data.description||'';$('status').value=data.status;$('featured').checked=data.is_featured;$('published').checked=data.is_published;const {data:gs}=await supabase.from('novel_genres').select('genre_id').eq('novel_id',id);const set=new Set((gs||[]).map(x=>x.genre_id));[...$('genre').options].forEach(o=>o.selected=set.has(o.value));scrollTo({top:0,behavior:'smooth'})}
window.deleteNovel=async id=>{if(!confirm('Delete this novel and all its chapters?'))return;const {error}=await supabase.from('novels').delete().eq('id',id);if(error)alert(error.message);else{resetNovel();await loadNovels();$('chapterPanel').classList.add('hidden')}}
function resetNovel(){$('novelForm').reset();$('novelId').value='';[...$('genre').options].forEach(o=>o.selected=false);$('novelMsg').textContent=''}
window.manageChapters=async id=>{selectedNovel=id;$('chapterPanel').classList.remove('hidden');$('chapterNovelId').value=id;const {data:n}=await supabase.from('novels').select('title').eq('id',id).single();$('chapterHeading').textContent=`Chapters — ${n?.title||''}`;await loadChapters();$('chapterPanel').scrollIntoView({behavior:'smooth'})}
async function loadChapters(){const {data,error}=await supabase.from('chapters').select('*').eq('novel_id',selectedNovel).order('chapter_number');$('chapterList').innerHTML=error?error.message:(data||[]).map(c=>`<div class="row"><div><strong>Chapter ${c.chapter_number}: ${esc(c.title)}</strong><small>${c.is_published?'Published':'Draft'}</small></div><div class="row-actions"><button class="btn secondary-btn" onclick="editChapter('${c.id}')">Edit</button><button class="btn danger-btn" onclick="deleteChapter('${c.id}')">Delete</button></div></div>`).join('')||'<p>No chapters yet.</p>'}
async function saveChapter(e){e.preventDefault();const id=$('chapterId').value;const payload={novel_id:$('chapterNovelId').value,chapter_number:Number($('chapterNumber').value),title:$('chapterTitle').value.trim(),content:$('chapterContent').value,is_published:$('chapterPublished').checked,updated_at:new Date().toISOString()};const res=id?await supabase.from('chapters').update(payload).eq('id',id):await supabase.from('chapters').insert(payload);if(res.error){$('chapterMsg').textContent=res.error.message;return}$('chapterMsg').textContent='Chapter saved.';resetChapter();await loadChapters()}
window.editChapter=async id=>{const {data}=await supabase.from('chapters').select('*').eq('id',id).single();if(!data)return;$('chapterId').value=data.id;$('chapterNovelId').value=data.novel_id;$('chapterNumber').value=data.chapter_number;$('chapterTitle').value=data.title;$('chapterContent').value=data.content;$('chapterPublished').checked=data.is_published;$('chapterHeading').textContent='Edit chapter'}
window.deleteChapter=async id=>{if(!confirm('Delete this chapter?'))return;const {error}=await supabase.from('chapters').delete().eq('id',id);if(error)alert(error.message);else await loadChapters()}
function resetChapter(){$('chapterForm').reset();$('chapterId').value='';$('chapterNovelId').value=selectedNovel||'';$('chapterMsg').textContent='';$('chapterHeading').textContent='Add chapter'}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}