const SUPABASE_URL="https://iuwmdwbdkegyzkppvngw.supabase.co",SUPABASE_KEY="sb_publishable_tXm0KC_lp8lSMh0QkdpCxA_jG_sm1hq";
const supabase=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id);
const searchModal=$("searchModal"),searchBtn=$("searchBtn"),closeSearch=$("closeSearch"),searchInput=$("novelSearch");
searchBtn?.addEventListener("click",()=>{searchModal.classList.add("open");setTimeout(()=>searchInput?.focus(),80)});
closeSearch?.addEventListener("click",()=>searchModal.classList.remove("open"));
searchModal?.addEventListener("click",e=>{if(e.target===searchModal)searchModal.classList.remove("open")});
document.addEventListener("keydown",e=>{if(e.key==="Escape")searchModal?.classList.remove("open")});
$("menuBtn")?.addEventListener("click",()=>$("mainNav")?.classList.toggle("open"));
$("mainNav")?.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>$("mainNav")?.classList.remove("open")));
function storyLink(slug){if(slug)location.href="novel-detail.html?slug="+encodeURIComponent(slug)}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",""":"&quot;","'":"&#039;"}[c]))}
function setStory(card,n){card.style.cursor="pointer";card.onclick=()=>storyLink(n.slug);const cover=card.querySelector(".cover");if(cover&&n.cover_url){cover.classList.add("has-real-cover");cover.style.backgroundImage="url('"+n.cover_url.replace(/'/g,"%27")+"')";cover.querySelector("span")?.style.setProperty("display","none");cover.querySelector("small")?.style.setProperty("display","none")}card.querySelector("h3").textContent=n.title;card.querySelector("p").textContent=n.synopsis||"A story waiting to be discovered.";card.querySelector(".tag").textContent=(n.novel_genres?.name||"STORY").toUpperCase();card.querySelector(".story-info>div").innerHTML="<span>★ "+Number(n.rating||0).toFixed(1)+"</span><span> • "+Number(n.chapter_count||0)+" chapters</span>"}
async function loadHome(){
 const params=new URLSearchParams(location.search),genre=params.get("genre");
 const q=await supabase.from("novels").select("*,novel_genres(name,slug)").eq("is_published",true).order("created_at",{ascending:false});
 if(q.error){console.error(q.error);$("storyEmpty").classList.remove("hidden");$("storyEmpty").textContent="We couldn't load stories. Please refresh.";return}
 let novels=q.data||[];
 if(genre)novels=novels.filter(n=>n.novel_genres?.slug===genre);
 const cards=[...document.querySelectorAll(".story")];cards.forEach((c,i)=>{if(novels[i]){c.style.display="";setStory(c,novels[i])}else c.style.display="none"});
 if(!novels.length)$("storyEmpty").classList.remove("hidden");else $("storyEmpty").classList.add("hidden");
 const all=(q.data||[]);
 const featured=all.find(n=>n.is_featured)||all[0];
 if(featured?.cover_url){$("heroCover").style.backgroundImage="linear-gradient(180deg,rgba(0,0,0,.05),rgba(0,0,0,.65)),url('"+featured.cover_url.replace(/'/g,"%27")+"')";$("heroCover").classList.add("real-hero");$("heroCover").querySelector("span")?.style.setProperty("display","none");$("heroCover").querySelector("strong").textContent=featured.title.toUpperCase();$("heroCover").querySelector("small").textContent="by "+(featured.author_name||"INKORA")}
 const genres=await supabase.from("novel_genres").select("*").eq("is_active",true).order("sort_order");
 if(!genres.error){$("genreStat").textContent=(genres.data||[]).length+"+";$("genreGrid").innerHTML=(genres.data||[]).map(g=>'<a href="novel.html?genre='+encodeURIComponent(g.slug)+'" class="genre"><span>'+esc(g.icon||"✦")+'</span><b>'+esc(g.name)+'</b><small>Explore stories</small></a>').join("")}
 const ranking=[...all].sort((a,b)=>(b.views||0)-(a.views||0)).slice(0,4);$("ranking").innerHTML=ranking.map((n,i)=>'<article onclick="storyLink('+JSON.stringify(n.slug)+')"><b>0'+(i+1)+'</b><div class="mini-cover" style="'+(n.cover_url?"background-image:url('"+n.cover_url.replace(/'/g,"%27")+"');background-size:cover;background-position:center":"")+'">'+(n.cover_url?"":"INKORA")+'</div><div><span class="tag">'+esc((n.novel_genres?.name||"STORY").toUpperCase())+'</span><h3>'+esc(n.title)+'</h3><p>by '+esc(n.author_name||"Unknown author")+'</p></div><strong>★ '+Number(n.rating||0).toFixed(1)+'</strong></article>').join("")||'<p class="section-note">No trending stories yet.</p>';
 await loadContinue();
}
async function loadContinue(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const r=await supabase.from("novel_reading_progress").select("chapter_number,progress_percent,novels(title,slug,author_name,cover_url,chapter_count)").eq("user_id",user.id).order("updated_at",{ascending:false}).limit(1).maybeSingle();if(r.error||!r.data?.novels)return;const d=r.data,n=d.novels,box=$("readingCard");box.onclick=()=>location.href="reader.html?slug="+encodeURIComponent(n.slug)+"&chapter="+d.chapter_number;box.style.cursor="pointer";if(n.cover_url){box.querySelector(".reading-cover").style.backgroundImage="url('"+n.cover_url.replace(/'/g,"%27")+"')";box.querySelector(".reading-cover").textContent=""}box.querySelector("h3").textContent=n.title;box.querySelector("p").textContent="Chapter "+d.chapter_number+" of "+(n.chapter_count||"—");box.querySelector(".progress i").style.width=Math.min(100,Number(d.progress_percent||0))+"%";box.querySelector("small").textContent=Math.round(Number(d.progress_percent||0))+"% complete";$("continueText").textContent="Continue your latest story exactly where you left off."}
searchInput?.addEventListener("input",async()=>{const q=searchInput.value.trim();const box=$("searchResults");if(!q){box.innerHTML="";return}const {data,error}=await supabase.from("novels").select("title,slug,author_name").eq("is_published",true).or("title.ilike.%"+q+"%,author_name.ilike.%"+q+"%").limit(8);if(error){box.innerHTML="<p>No results.</p>";return}box.innerHTML=(data||[]).map(n=>'<button data-slug="'+esc(n.slug)+'"><b>'+esc(n.title)+'</b><small>by '+esc(n.author_name)+'</small></button>').join("")||"<p>No stories found.</p>";box.querySelectorAll("button").forEach(b=>b.onclick=()=>storyLink(b.dataset.slug))});
document.querySelectorAll(".suggestions span").forEach(s=>s.onclick=()=>{searchInput.value=s.textContent;searchInput.dispatchEvent(new Event("input"))});
$("newsletterForm")?.addEventListener("submit",e=>{e.preventDefault();const email=$("newsletterEmail").value.trim();if(!email)return;localStorage.setItem("inkora_newsletter_email",email);$("newsletterStatus").textContent="You're on the list. Welcome to INKORA.";e.target.reset()});
async function setupAccount(){const btn=$("accountBtn"),adminNav=$("adminNav");const {data:{user}}=await supabase.auth.getUser();if(!user){btn.textContent="G";btn.title="Sign in";btn.onclick=()=>location.href="index.html";return}btn.textContent=(user.email||"G").charAt(0).toUpperCase();btn.title=user.email||"Account";const {data}=await supabase.from("profiles").select("role").eq("id",user.id).maybeSingle();if(data?.role==="admin")adminNav?.classList.remove("hidden");btn.onclick=()=>location.href=data?.role==="admin"?"admin.html":"library.html"}
setupAccount();loadHome();