const $=id=>document.getElementById(id);let novels=[],genres=[],user=null,currentNovel=null,currentChapter=0,signup=false;

document.addEventListener('DOMContentLoaded',async()=>{try{$('year').textContent=new Date().getFullYear();bindUI();if(!window.supabaseReady||!supabase){showStartupError('The reading service could not start. Please refresh the page.');return}await Promise.race([restoreAuth(),timeout(6000)]);await Promise.race([loadGenres(),timeout(6000)]);await Promise.race([loadNovels(),timeout(6000)]);}catch(e){console.error(e);showStartupError('The app took too long to connect. Please refresh and try again.')}finally{setTimeout(()=>{$('loader')?.classList.add('hide')},250)}});
function timeout(ms){return new Promise(r=>setTimeout(r,ms))}
function showStartupError(msg){const g=$('novelGrid');if(g)g.innerHTML=`<div class="empty">${esc(msg)}<br><button class="primary" style="margin-top:15px" onclick="location.reload()">Refresh</button></div>`}
function bindUI(){$('authBtn').onclick=()=>location.hash='account';$('search').oninput=()=>renderNovels($('search').value.trim().toLowerCase());$('switchAuth').onclick=()=>{signup=!signup;document.querySelector('.auth-section form').classList.toggle('signup-mode',signup);$('authName').style.display=signup?'block':'none';$('switchAuth').textContent=signup?'Already have an account? Sign in':'Create an account'};$('authForm').onsubmit=authSubmit;$('closeReader').onclick=closeReader;$('readerFont').onclick=()=>$('chapterContent').classList.toggle('large');$('prevChapter').onclick=()=>openChapter(currentChapter-1);$('nextChapter').onclick=()=>openChapter(currentChapter+1);document.querySelectorAll('[data-genre-link]').forEach(x=>x.onclick=()=>filterGenre(x.dataset.genreLink));$('genres').addEventListener('click',e=>{if(e.target.dataset.genre){filterGenre(e.target.dataset.genre);document.querySelectorAll('#genres button').forEach(b=>b.classList.remove('active'));e.target.classList.add('active')}})}
async function restoreAuth(){const {data}=await supabase.auth.getUser();user=data.user||null;supabase.auth.onAuthStateChange((_e,s)=>{user=s?.user||null;loadLibrary()});loadLibrary()}
async function authSubmit(e){e.preventDefault();const email=$('authEmail').value.trim(),password=$('authPassword').value;$('authStatus').textContent='Please wait…';let res;if(signup)res=await supabase.auth.signUp({email,password,options:{data:{display_name:$('authName').value.trim()}}});else res=await supabase.auth.signInWithPassword({email,password});if(res.error){$('authStatus').textContent=res.error.message;return}$('authStatus').textContent=signup?'Account created. Check your email if confirmation is enabled.':'Signed in successfully.';if(!signup){user=res.data.user;loadLibrary()}}
async function loadGenres(){const {data,error}=await supabase.from('genres').select('id,name,slug').order('name');if(error){console.error(error);return}genres=data||[]}
async function loadNovels(){const {data,error}=await supabase.from('novels').select('id,title,slug,author_name,description,cover_url,status,rating,views,is_featured').eq('is_published',true).order('is_featured',{ascending:false}).order('created_at',{ascending:false});if(error){console.error(error);renderNovels();return}novels=data||[];renderNovels()}
function renderNovels(term=''){const grid=$('novelGrid');let list=novels.filter(n=>!term||`${n.title} ${n.author_name} ${n.description||''}`.toLowerCase().includes(term));$('resultCount').textContent=list.length?`${list.length} novel${list.length===1?'':'s'}`:'';grid.innerHTML=list.length?list.map(n=>novelCard(n)).join(''):'<div class="empty">No published novels found yet. Your library is ready for new stories.</div>'}
function novelCard(n){return `<article class="novel-card" onclick="openNovel('${n.id}')"><div class="cover">${n.cover_url?`<img src="${attr(n.cover_url)}" alt="${attr(n.title)}">`:`<div class="cover-placeholder">${esc(n.title)}</div>`}</div><div class="novel-info"><h3>${esc(n.title)}</h3><p>${esc(n.author_name||'Unknown author')}</p><div class="novel-meta"><span>★ ${Number(n.rating||0).toFixed(1)}</span><span>${Number(n.views||0).toLocaleString()} views</span></div></div></article>`}
async function filterGenre(name){if(name==='all'){renderNovels();return}const g=genres.find(x=>x.name.toLowerCase()===name.toLowerCase()||x.slug===name.toLowerCase());if(!g){renderNovels(name.toLowerCase());return}const {data}=await supabase.from('novel_genres').select('novel_id').eq('genre_id',g.id);const ids=new Set((data||[]).map(x=>x.novel_id));const list=novels.filter(n=>ids.has(n.id));$('novelGrid').innerHTML=list.length?list.map(n=>novelCard(n)).join(''):'<div class="empty">No stories in this genre yet.</div>'}
window.openNovel=async id=>{const n=novels.find(x=>x.id===id);if(!n)return;const {data}=await supabase.from('chapters').select('id,chapter_number,title').eq('novel_id',id).eq('is_published',true).order('chapter_number');if(!data?.length){toast('This novel has no published chapters yet.');return}currentNovel={...n,chapters:data};currentChapter=0;await openChapter(0)};
async function openChapter(index){if(!currentNovel||index<0||index>=currentNovel.chapters.length)return;currentChapter=index;const c=currentNovel.chapters[index];const {data}=await supabase.from('chapters').select('content,title,chapter_number').eq('id',c.id).single();if(!data)return;$('readerTitle').textContent=currentNovel.title;$('readerMeta').textContent=`${currentNovel.author_name||'Unknown author'} • Chapter ${data.chapter_number}`;$('chapterTitle').textContent=data.title;$('chapterContent').innerHTML=paragraphs(data.content);$('prevChapter').disabled=index===0;$('nextChapter').disabled=index===currentNovel.chapters.length-1;$('reader').classList.remove('hidden');document.body.style.overflow='hidden';if(user)saveProgress(c.id,index)}
async function saveProgress(chapterId,index){await supabase.from('reading_progress').upsert({user_id:user.id,novel_id:currentNovel.id,chapter_id:chapterId,progress_percent:Math.round(((index+1)/currentNovel.chapters.length)*100),updated_at:new Date().toISOString()})}
function closeReader(){$('reader').classList.add('hidden');document.body.style.overflow='';loadLibrary()}
async function loadLibrary(){const grid=$('libraryGrid');if(!user){grid.innerHTML='<div class="empty">Sign in to save novels and continue reading across devices.</div>';return}const {data}=await supabase.from('bookmarks').select('novel_id').eq('user_id',user.id);const ids=new Set((data||[]).map(x=>x.novel_id));const list=novels.filter(n=>ids.has(n.id));grid.innerHTML=list.length?list.map(n=>novelCard(n)).join(''):'<div class="empty">Your library is empty. Open a novel and add it to your reading list.</div>'}
function paragraphs(t=''){return esc(t).split(/\n\s*\n/).map(p=>`<p>${p.replace(/\n/g,'<br>')}</p>`).join('')}
function toast(t){let x=document.createElement('div');x.className='toast show';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2400)}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function attr(v=''){return esc(v)}
